<?php

namespace Database\Seeders;

use App\Models\Inquiry;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class InquirySeeder extends Seeder
{
    public function run(): void
    {
        $records = [
            // --- STARTUP INQUIRIES ---
            [
                'type' => 'startup',
                'name' => 'Aarav Sharma',
                'email' => 'aarav.sharma@zetavolt.io',
                'phone' => '+91 98201 44521',
                'company' => 'ZetaVolt Mobility Systems',
                'status' => 'New',
                'days_ago' => 0,
                'payload' => [
                    'founderName' => 'Aarav Sharma',
                    'company' => 'ZetaVolt Mobility Systems',
                    'designation' => 'Co-Founder & CEO',
                    'email' => 'aarav.sharma@zetavolt.io',
                    'mobile' => '+91 98201 44521',
                    'website' => 'https://zetavolt.example.com',
                    'linkedIn' => 'https://linkedin.com/in/aarav-sharma-ev',
                    'city' => 'Bengaluru',
                    'sector' => 'CleanTech / EV Fast-Charging',
                    'businessStage' => 'growth',
                    'tractionSummary' => '₹3.2 Cr ARR, operating 45 fast-charging hubs across Bengaluru and Pune with 68% MoM recurring fleet utilization.',
                    'capitalSought' => '5-25cr',
                    'capitalUse' => 'Expanding charging infrastructure grid to 120 hubs and proprietary battery diagnostic software rollout.',
                    'declaration' => true,
                    'consent' => true,
                    'newsletterConsent' => true,
                ],
            ],
            [
                'type' => 'startup',
                'name' => 'Priya Patel',
                'email' => 'priya@kisanlink.tech',
                'phone' => '+91 97123 55890',
                'company' => 'KisanLink Agritech Pvt Ltd',
                'status' => 'Reviewed',
                'days_ago' => 1,
                'payload' => [
                    'founderName' => 'Priya Patel',
                    'company' => 'KisanLink Agritech Pvt Ltd',
                    'designation' => 'Founder',
                    'email' => 'priya@kisanlink.tech',
                    'mobile' => '+91 97123 55890',
                    'website' => 'https://kisanlink.example.com',
                    'city' => 'Ahmedabad',
                    'sector' => 'AgriTech Supply Chain',
                    'businessStage' => 'early-revenue',
                    'tractionSummary' => 'Direct farmer-to-mandi procurement software across 12 districts in Gujarat. Monthly GMV ₹1.8 Cr with 8% take rate.',
                    'capitalSought' => '1-5cr',
                    'capitalUse' => 'Warehouse cold-storage aggregation nodes and farmer onboarding app enhancement.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'startup',
                'name' => 'Rohan Varma',
                'email' => 'rohan@docuhealth.ai',
                'phone' => '+91 98450 12349',
                'company' => 'DocuHealth Intelligence',
                'status' => 'Contacted',
                'days_ago' => 3,
                'payload' => [
                    'founderName' => 'Rohan Varma',
                    'company' => 'DocuHealth Intelligence',
                    'designation' => 'CEO & Technical Founder',
                    'email' => 'rohan@docuhealth.ai',
                    'mobile' => '+91 98450 12349',
                    'city' => 'Hyderabad',
                    'sector' => 'HealthTech / AI Diagnostics',
                    'businessStage' => 'growth',
                    'tractionSummary' => 'Serving 40+ hospitals with automated radiology scan triaging; ISO 13485 certified platform.',
                    'capitalSought' => '5-25cr',
                    'capitalUse' => 'Clinical trials for oncology module and US FDA 510(k) pathway preparation.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'startup',
                'name' => 'Ananya Sengupta',
                'email' => 'ananya@finpulse.in',
                'phone' => '+91 98310 99881',
                'company' => 'FinPulse Embedded Credit',
                'status' => 'New',
                'days_ago' => 4,
                'payload' => [
                    'founderName' => 'Ananya Sengupta',
                    'company' => 'FinPulse Embedded Credit',
                    'designation' => 'Co-Founder',
                    'email' => 'ananya@finpulse.in',
                    'mobile' => '+91 98310 99881',
                    'city' => 'Kolkata',
                    'sector' => 'Fintech B2B Lending',
                    'businessStage' => 'early-revenue',
                    'tractionSummary' => '₹45 Lakh disbursed loan book in pilot phase, default rate under 0.8%.',
                    'capitalSought' => '1-5cr',
                    'capitalUse' => 'First-loss default guarantee pool and NBFC underwriting integration.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'startup',
                'name' => 'Devendra Rathore',
                'email' => 'dev@aeronav.space',
                'phone' => '+91 98290 77123',
                'company' => 'AeroNav Space Labs',
                'status' => 'Reviewed',
                'days_ago' => 6,
                'payload' => [
                    'founderName' => 'Devendra Rathore',
                    'company' => 'AeroNav Space Labs',
                    'designation' => 'Chief Technology Officer',
                    'email' => 'dev@aeronav.space',
                    'mobile' => '+91 98290 77123',
                    'city' => 'Jaipur',
                    'sector' => 'DeepTech / Aerospace',
                    'businessStage' => 'early-revenue',
                    'tractionSummary' => 'Payload contract signed with IN-SPACe; optical communication module bench-tested.',
                    'capitalSought' => '5-25cr',
                    'capitalUse' => 'Cleanroom satellite assembly facility and orbital launch reservation.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'startup',
                'name' => 'Kunal Kashyap',
                'email' => 'kunal@hyperlogix.co',
                'phone' => '+91 99001 88234',
                'company' => 'HyperLogix Supply Automation',
                'status' => 'Closed',
                'days_ago' => 12,
                'payload' => [
                    'founderName' => 'Kunal Kashyap',
                    'company' => 'HyperLogix Supply Automation',
                    'designation' => 'Founder & Managing Director',
                    'email' => 'kunal@hyperlogix.co',
                    'mobile' => '+91 99001 88234',
                    'city' => 'Gurugram',
                    'sector' => 'Logistics Automation',
                    'businessStage' => 'scale',
                    'tractionSummary' => 'Series A completed with peer syndicate; round closed at ₹30 Cr valuation.',
                    'capitalSought' => '25cr-plus',
                    'capitalUse' => 'Tier 2 distribution expansion.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'startup',
                'name' => 'Crypto Moon Bot',
                'email' => 'pump@telegram-crypto-bot.xyz',
                'phone' => '+91 90000 00000',
                'company' => '1000x Returns Guaranteed',
                'status' => 'Spam',
                'days_ago' => 14,
                'payload' => [
                    'founderName' => 'Crypto Moon Bot',
                    'company' => '1000x Returns Guaranteed',
                    'designation' => 'Automated Bot',
                    'email' => 'pump@telegram-crypto-bot.xyz',
                    'mobile' => '+91 90000 00000',
                    'city' => 'Unknown',
                    'sector' => 'Crypto Spam',
                    'businessStage' => 'other',
                    'tractionSummary' => 'Buy coin now for instant wealth link in telegram channel.',
                    'capitalSought' => 'under-1cr',
                    'capitalUse' => 'Liquidity pool seeding.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],

            // --- MSME INQUIRIES ---
            [
                'type' => 'msme',
                'name' => 'Rajesh Singhania',
                'email' => 'r.singhania@singhaniagears.com',
                'phone' => '+91 98140 23456',
                'company' => 'Singhania Precision Gears Ltd',
                'status' => 'New',
                'days_ago' => 1,
                'payload' => [
                    'contactName' => 'Rajesh Singhania',
                    'company' => 'Singhania Precision Gears Ltd',
                    'designation' => 'Managing Director',
                    'email' => 'r.singhania@singhaniagears.com',
                    'mobile' => '+91 98140 23456',
                    'website' => 'https://singhaniagears.example.com',
                    'city' => 'Ludhiana',
                    'industry' => 'Automotive Component Manufacturing',
                    'businessAge' => '15-plus',
                    'revenueRange' => '25cr-plus',
                    'capitalRequirement' => '5-25cr',
                    'capitalPurpose' => 'Setting up a dedicated CNC transmission machining line for Tier-1 EV powertrain export contracts.',
                    'declaration' => true,
                    'consent' => true,
                    'newsletterConsent' => true,
                ],
            ],
            [
                'type' => 'msme',
                'name' => 'Vikram Malhotra',
                'email' => 'vmalhotra@apexpolymers.in',
                'phone' => '+91 98260 88990',
                'company' => 'Apex Polymers & Resins',
                'status' => 'Reviewed',
                'days_ago' => 2,
                'payload' => [
                    'contactName' => 'Vikram Malhotra',
                    'company' => 'Apex Polymers & Resins',
                    'designation' => 'Partner & COO',
                    'email' => 'vmalhotra@apexpolymers.in',
                    'mobile' => '+91 98260 88990',
                    'city' => 'Vadodara',
                    'industry' => 'Speciality Polymer Packaging',
                    'businessAge' => '8-15',
                    'revenueRange' => '5-25cr',
                    'capitalRequirement' => '5-25cr',
                    'capitalPurpose' => 'Biodegradable film extrusion plant setup and working capital rationalisation.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'msme',
                'name' => 'Sunita Rao',
                'email' => 'sunita.rao@deccancoatings.com',
                'phone' => '+91 94401 56789',
                'company' => 'Deccan Electro-Coatings',
                'status' => 'Contacted',
                'days_ago' => 5,
                'payload' => [
                    'contactName' => 'Sunita Rao',
                    'company' => 'Deccan Electro-Coatings',
                    'designation' => 'Executive Director',
                    'email' => 'sunita.rao@deccancoatings.com',
                    'mobile' => '+91 94401 56789',
                    'city' => 'Hyderabad',
                    'industry' => 'Industrial Surface Treatment',
                    'businessAge' => '3-7',
                    'revenueRange' => '1-5cr',
                    'capitalRequirement' => '1-5cr',
                    'capitalPurpose' => 'Automated cathode electro-deposition line for defense aerospace components.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'msme',
                'name' => 'Mukesh Choksi',
                'email' => 'mchoksi@choksitex.in',
                'phone' => '+91 98251 33445',
                'company' => 'Choksi Technical Textiles',
                'status' => 'Closed',
                'days_ago' => 9,
                'payload' => [
                    'contactName' => 'Mukesh Choksi',
                    'company' => 'Choksi Technical Textiles',
                    'designation' => 'Promoter & Chairman',
                    'email' => 'mchoksi@choksitex.in',
                    'mobile' => '+91 98251 33445',
                    'city' => 'Surat',
                    'industry' => 'Geotextiles & Filtration Media',
                    'businessAge' => '15-plus',
                    'revenueRange' => '25cr-plus',
                    'capitalRequirement' => '25cr-plus',
                    'capitalPurpose' => 'Structured debt refinancing and partner equity buyback successfully concluded.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'msme',
                'name' => 'Pradeep Kulkarni',
                'email' => 'pradeep@kulkarnifoundry.com',
                'phone' => '+91 98220 11992',
                'company' => 'Kulkarni Precision Castings',
                'status' => 'New',
                'days_ago' => 11,
                'payload' => [
                    'contactName' => 'Pradeep Kulkarni',
                    'company' => 'Kulkarni Precision Castings',
                    'designation' => 'Promoter Director',
                    'email' => 'pradeep@kulkarnifoundry.com',
                    'mobile' => '+91 98220 11992',
                    'city' => 'Kolhapur',
                    'industry' => 'SGI Grey Iron Foundries',
                    'businessAge' => '8-15',
                    'revenueRange' => '5-25cr',
                    'capitalRequirement' => '1-5cr',
                    'capitalPurpose' => 'Induction furnace energy efficiency retrofitting to reduce per-ton melting cost.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],

            // --- INVESTOR INQUIRIES ---
            [
                'type' => 'investor',
                'name' => 'Siddharth Mehra',
                'email' => 'siddharth@mehrafamilyoffice.in',
                'phone' => '+91 98200 12003',
                'company' => 'Mehra Family Investment Office',
                'status' => 'New',
                'days_ago' => 0,
                'payload' => [
                    'name' => 'Siddharth Mehra',
                    'organisation' => 'Mehra Family Investment Office',
                    'designation' => 'Chief Investment Officer',
                    'email' => 'siddharth@mehrafamilyoffice.in',
                    'mobile' => '+91 98200 12003',
                    'linkedIn' => 'https://linkedin.com/in/siddharth-mehra-fo',
                    'location' => 'Mumbai / Nariman Point',
                    'investorType' => 'family-office',
                    'preferredSectors' => 'Speciality Chemicals, Engineering Exports, MSME Industrial Tech',
                    'preferredStage' => 'Profitable MSMEs seeking growth equity (EBITDA ₹5 Cr+)',
                    'ticketSize' => '5-25cr',
                    'strategicCapabilities' => 'Global distribution channels in Europe and corporate governance advisory.',
                    'declaration' => true,
                    'consent' => true,
                    'newsletterConsent' => true,
                ],
            ],
            [
                'type' => 'investor',
                'name' => 'Neha Kapoor',
                'email' => 'neha.kapoor@bluehorizoncap.com',
                'phone' => '+91 98101 44556',
                'company' => 'BlueHorizon Growth Fund',
                'status' => 'Reviewed',
                'days_ago' => 2,
                'payload' => [
                    'name' => 'Neha Kapoor',
                    'organisation' => 'BlueHorizon Growth Fund',
                    'designation' => 'Principal — Growth Equity',
                    'email' => 'neha.kapoor@bluehorizoncap.com',
                    'mobile' => '+91 98101 44556',
                    'location' => 'New Delhi',
                    'investorType' => 'fund',
                    'preferredSectors' => 'Enterprise SaaS, B2B Supply Chain, Agritech Infrastructure',
                    'preferredStage' => 'Series A to B with clear unit economics',
                    'ticketSize' => '25cr-plus',
                    'strategicCapabilities' => 'Syndicate co-investment, US market expansion corridor.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'investor',
                'name' => 'Rajiv Nambiar',
                'email' => 'rajiv@nambiarcapital.sg',
                'phone' => '+65 9123 4567',
                'company' => 'Nambiar Global Holdings',
                'status' => 'Contacted',
                'days_ago' => 4,
                'payload' => [
                    'name' => 'Rajiv Nambiar',
                    'organisation' => 'Nambiar Global Holdings',
                    'designation' => 'Managing Director',
                    'email' => 'rajiv@nambiarcapital.sg',
                    'mobile' => '+65 9123 4567',
                    'location' => 'Singapore / Bengaluru',
                    'investorType' => 'individual',
                    'preferredSectors' => 'Fintech, Healthcare Infrastructure, Green Logistics',
                    'preferredStage' => 'Pre-Series A / Strategic Bridge',
                    'ticketSize' => '1-5cr',
                    'strategicCapabilities' => 'Cross-border ASEAN market access and regulatory licensing assistance.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'investor',
                'name' => 'Aditya Somani',
                'email' => 'aditya@somanicorp.com',
                'phone' => '+91 98300 66778',
                'company' => 'Somani Industrial Enterprises',
                'status' => 'Closed',
                'days_ago' => 15,
                'payload' => [
                    'name' => 'Aditya Somani',
                    'organisation' => 'Somani Industrial Enterprises',
                    'designation' => 'Head of Corporate Venturing',
                    'email' => 'aditya@somanicorp.com',
                    'mobile' => '+91 98300 66778',
                    'location' => 'Kolkata',
                    'investorType' => 'corporate',
                    'preferredSectors' => 'Heavy Engineering, Energy Transition, Scrap Recycling Tech',
                    'preferredStage' => 'Strategic majority or minority stake in operating MSMEs',
                    'ticketSize' => '25cr-plus',
                    'strategicCapabilities' => 'Vendor ecosystem absorption and working capital line support.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],

            // --- M&A ADVISORY INQUIRIES ---
            [
                'type' => 'ma',
                'name' => 'Gautam Desai',
                'email' => 'g.desai@transindiapharma.com',
                'phone' => '+91 98202 77889',
                'company' => 'TransIndia Pharma Formulation Ltd',
                'status' => 'New',
                'days_ago' => 1,
                'payload' => [
                    'contactName' => 'Gautam Desai',
                    'organisation' => 'TransIndia Pharma Formulation Ltd',
                    'designation' => 'Executive Vice President — M&A',
                    'email' => 'g.desai@transindiapharma.com',
                    'mobile' => '+91 98202 77889',
                    'website' => 'https://transindiapharma.example.com',
                    'transactionSide' => 'sell-side',
                    'transactionType' => 'Divestment of sterile injectable manufacturing plant',
                    'sector' => 'Pharmaceuticals & APIs',
                    'geography' => 'Western India / Gujarat Special Economic Zone',
                    'transactionRange' => '25cr-plus',
                    'confidentialSummary' => 'WHO-GMP and USFDA compliant formulation facility looking for strategic sale or controlling interest acquisition by multinational CDMO.',
                    'declaration' => true,
                    'consent' => true,
                    'newsletterConsent' => true,
                ],
            ],
            [
                'type' => 'ma',
                'name' => 'Alok Mukherjee',
                'email' => 'alok@easterncastings.co.in',
                'phone' => '+91 98311 22334',
                'company' => 'Eastern Precision Castings Corp',
                'status' => 'Reviewed',
                'days_ago' => 3,
                'payload' => [
                    'contactName' => 'Alok Mukherjee',
                    'organisation' => 'Eastern Precision Castings Corp',
                    'designation' => 'Chairman & Promoter',
                    'email' => 'alok@easterncastings.co.in',
                    'mobile' => '+91 98311 22334',
                    'transactionSide' => 'sell-side',
                    'transactionType' => 'Full promoter succession sale / buyout',
                    'sector' => 'Heavy Engineering / Railway Components',
                    'geography' => 'West Bengal / Durgapur Industrial Corridor',
                    'transactionRange' => '5-25cr',
                    'confidentialSummary' => '30-year operational track record supplying Class-A cast bogie parts to Indian Railways. Debt-free company.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'ma',
                'name' => 'Sameer Nair',
                'email' => 'sameer@southerncoldchain.com',
                'phone' => '+91 98470 55667',
                'company' => 'Southern Agro Cold Chain Pvt Ltd',
                'status' => 'Contacted',
                'days_ago' => 6,
                'payload' => [
                    'contactName' => 'Sameer Nair',
                    'organisation' => 'Southern Agro Cold Chain Pvt Ltd',
                    'designation' => 'CEO',
                    'email' => 'sameer@southerncoldchain.com',
                    'mobile' => '+91 98470 55667',
                    'transactionSide' => 'buy-side',
                    'transactionType' => 'Strategic acquisition of regional reefers & cold warehouses',
                    'sector' => 'Perishable Logistics',
                    'geography' => 'Tamil Nadu, Kerala & Andhra Pradesh',
                    'transactionRange' => '5-25cr',
                    'confidentialSummary' => 'Looking to acquire 2-3 regional cold store operators with 10,000 MT capacity each.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'ma',
                'name' => 'Farhan Qureshi',
                'email' => 'farhan@apextelecominfra.com',
                'phone' => '+91 98110 33442',
                'company' => 'Apex Fiber Infrastructure',
                'status' => 'Closed',
                'days_ago' => 16,
                'payload' => [
                    'contactName' => 'Farhan Qureshi',
                    'organisation' => 'Apex Fiber Infrastructure',
                    'designation' => 'Director — Corporate Strategy',
                    'email' => 'farhan@apextelecominfra.com',
                    'mobile' => '+91 98110 33442',
                    'transactionSide' => 'partnership',
                    'transactionType' => 'JV with telecom infra tower operator',
                    'sector' => 'Telecom Infrastructure / Dark Fiber',
                    'geography' => 'North India (NCR, Haryana, Punjab)',
                    'transactionRange' => '25cr-plus',
                    'confidentialSummary' => 'Concluded equity swap and fiber lease deal with public telecom company.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],

            // --- CONTACT FORM INQUIRIES ---
            [
                'type' => 'contact',
                'name' => 'Pooja Bhatt',
                'email' => 'pooja.bhatt@capitaledge.in',
                'phone' => '+91 98205 11223',
                'company' => 'CapitalEdge Advisory LLP',
                'status' => 'New',
                'days_ago' => 0,
                'payload' => [
                    'name' => 'Pooja Bhatt',
                    'organisation' => 'CapitalEdge Advisory LLP',
                    'email' => 'pooja.bhatt@capitaledge.in',
                    'mobile' => '+91 98205 11223',
                    'inquiryCategory' => 'investor',
                    'message' => 'We represent several mid-market family offices interested in reviewing deal flow in the green energy and manufacturing corridors evaluated by BIC.',
                    'declaration' => true,
                    'consent' => true,
                    'newsletterConsent' => true,
                ],
            ],
            [
                'type' => 'contact',
                'name' => 'Manoj Kulkarni',
                'email' => 'mkulkarni@kulkarniglobal.com',
                'phone' => '+91 98221 44556',
                'company' => 'Kulkarni Global Trading',
                'status' => 'Reviewed',
                'days_ago' => 2,
                'payload' => [
                    'name' => 'Manoj Kulkarni',
                    'organisation' => 'Kulkarni Global Trading',
                    'email' => 'mkulkarni@kulkarniglobal.com',
                    'mobile' => '+91 98221 44556',
                    'inquiryCategory' => 'msme',
                    'message' => 'Seeking exploratory consultation regarding pre-IPO private equity structuring for our agro-export business ahead of an NSE Emerge filing.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'contact',
                'name' => 'Deepa Krishnan',
                'email' => 'deepa.k@chennaicap.org',
                'phone' => '+91 94440 88776',
                'company' => 'Chennai Angel Network',
                'status' => 'Contacted',
                'days_ago' => 4,
                'payload' => [
                    'name' => 'Deepa Krishnan',
                    'organisation' => 'Chennai Angel Network',
                    'email' => 'deepa.k@chennaicap.org',
                    'mobile' => '+91 94440 88776',
                    'inquiryCategory' => 'startup',
                    'message' => 'Interested in establishing a co-investment framework with BIC for institutional bridge rounds in South Indian hardware and manufacturing startups.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'contact',
                'name' => 'Amitabh Swamy',
                'email' => 'amitabh.swamy@delhitrust.in',
                'phone' => '+91 98180 55443',
                'company' => 'Delhi Corporate Trusteeship',
                'status' => 'Closed',
                'days_ago' => 10,
                'payload' => [
                    'name' => 'Amitabh Swamy',
                    'organisation' => 'Delhi Corporate Trusteeship',
                    'email' => 'amitabh.swamy@delhitrust.in',
                    'mobile' => '+91 98180 55443',
                    'inquiryCategory' => 'ma',
                    'message' => 'Confidential request regarding asset escrow and escrow agent mechanisms for cross-border transactions.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
            [
                'type' => 'contact',
                'name' => 'Harkishan Lal',
                'email' => 'seo-guru-spammer@cheapbacklinks.org',
                'phone' => '+91 91111 22222',
                'company' => 'Top Rank SEO Agency',
                'status' => 'Spam',
                'days_ago' => 18,
                'payload' => [
                    'name' => 'Harkishan Lal',
                    'organisation' => 'Top Rank SEO Agency',
                    'email' => 'seo-guru-spammer@cheapbacklinks.org',
                    'mobile' => '+91 91111 22222',
                    'inquiryCategory' => 'other',
                    'message' => 'We can rank your website #1 on Google in 7 days for only $99! Reply to get special offer today.',
                    'declaration' => true,
                    'consent' => true,
                ],
            ],
        ];

        // Ensure we generate at least 32 records total so pagination (> 25 per page) activates!
        // We will duplicate some with different references and dates
        $typesList = ['startup', 'msme', 'investor', 'ma', 'contact'];
        $cities = ['Mumbai', 'Bengaluru', 'Delhi NCR', 'Pune', 'Hyderabad', 'Chennai', 'Ahmedabad', 'Kolkata', 'Chandigarh', 'Indore'];
        $statuses = ['New', 'Reviewed', 'Contacted', 'Closed'];

        for ($i = 1; $i <= 15; $i++) {
            $type = $typesList[($i - 1) % count($typesList)];
            $status = $statuses[($i - 1) % count($statuses)];
            $city = $cities[($i - 1) % count($cities)];
            $days = $i + 5;

            $records[] = [
                'type' => $type,
                'name' => "Partner Exec {$i}",
                'email' => "executive_{$i}@enterprise-node.in",
                'phone' => "+91 98" . str_pad($i, 8, '0', STR_PAD_LEFT),
                'company' => "Bharat Dynamic Systems Unit {$i}",
                'status' => $status,
                'days_ago' => $days,
                'payload' => [
                    'name' => "Partner Exec {$i}",
                    'company' => "Bharat Dynamic Systems Unit {$i}",
                    'email' => "executive_{$i}@enterprise-node.in",
                    'mobile' => "+91 98" . str_pad($i, 8, '0', STR_PAD_LEFT),
                    'city' => $city,
                    'note' => "Institutional inquiry record #{$i} generated for pipeline analysis and stress testing.",
                    'declaration' => true,
                    'consent' => true,
                ],
            ];
        }

        // Clean slate and insert
        Inquiry::truncate();

        foreach ($records as $index => $item) {
            $created = now()->subDays($item['days_ago'])->subMinutes($index * 17);
            Inquiry::create([
                'reference' => 'BIC-' . $created->format('Ymd') . '-' . Str::upper(Str::random(6)),
                'type' => $item['type'],
                'name' => $item['name'],
                'email' => $item['email'],
                'phone' => $item['phone'],
                'company' => $item['company'],
                'payload' => $item['payload'],
                'document_path' => null,
                'status' => $item['status'],
                'created_at' => $created,
                'updated_at' => $created,
            ]);
        }
    }
}
