@extends('layouts.admin')
@section('title', ($insight->exists ? 'Edit' : 'Create').' Insight | BIC')
@section('admin-content')
<div class="admin-title"><div><p class="eyebrow">Insights CMS</p><h1>{{ $insight->exists ? 'Edit Insight' : 'Create Insight' }}</h1></div></div>
<form class="admin-form" method="post" enctype="multipart/form-data" action="{{ $insight->exists ? route('admin.insights.update', $insight) : route('admin.insights.store') }}">@csrf @if($insight->exists)@method('PUT')@endif
    <div class="admin-form-grid"><label>Title<input name="title" value="{{ old('title', $insight->title) }}" required></label><label>Slug<input name="slug" value="{{ old('slug', $insight->slug) }}" placeholder="Generated from title if empty"></label><label class="wide">Summary<textarea name="summary" required>{{ old('summary', $insight->summary) }}</textarea></label><label class="wide">Body<textarea name="body" rows="14" required>{{ old('body', $insight->body) }}</textarea></label><label>Cover image<input name="cover_upload" type="file" accept="image/*"></label><label>Alt text<input name="alt_text" value="{{ old('alt_text', $insight->alt_text) }}"></label><label>Author<input name="author" value="{{ old('author', $insight->author) }}"></label><label>Category<input name="category" value="{{ old('category', $insight->category) }}"></label><label>Status<select name="status">@foreach(['draft','published','archived'] as $status)<option @selected(old('status',$insight->status ?: 'draft')===$status)>{{ $status }}</option>@endforeach</select></label><label>Publish date<input name="published_at" type="datetime-local" value="{{ old('published_at', $insight->published_at?->format('Y-m-d\TH:i')) }}"></label><label class="admin-check"><input name="featured" type="checkbox" value="1" @checked(old('featured',$insight->featured))> Featured</label><label class="wide">SEO title<input name="seo_title" value="{{ old('seo_title', $insight->seo_title) }}"></label><label class="wide">SEO description<textarea name="seo_description">{{ old('seo_description', $insight->seo_description) }}</textarea></label></div>
    @if($errors->any())<div class="admin-error"><strong>Review the form:</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif<button class="admin-primary" type="submit">Save Insight</button>
</form>
@endsection

